INSERT INTO `user` (id, username, password)
VALUES (1, 'Mike', 'password'),
       (2, 'Jane', 'password'),
       (3, 'Jack', 'password'),
       (4, 'Bill', 'password'),
       (5, 'Emily', 'password'),
       (6, 'Alex', 'password'),
       (7, 'Sarah', 'password'),
       (8, 'Chris', 'password'),
       (9, 'Olivia', 'password'),
       (10, 'Daniel', 'password'),
       (11, 'Sophia', 'password'),
       (12, 'David', 'password'),
       (13, 'Emma', 'password'),
       (14, 'James', 'password'),
       (15, 'Lily', 'password'),
       (16, 'Jacob', 'password'),
       (17, 'Ava', 'password'),
       (18, 'Matthew', 'password'),
       (19, 'Grace', 'password'),
       (20, 'Samuel', 'password');